apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lqda
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lqda
    app.kubernetes.io/part-of: ci10t-786-0049-app
  name: devfile-sample-lqda
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lqda
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lqda
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0049-tenant/ci10t-786-0049-app/devfile-sample-lqda@sha256:9c475a2c6aff548e591c1a1a95eb76b5fb97405c6c8509f61284677d4b4b6214
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
